databases:
  - name: text_analysis_db
    region: singapore
    plan: free
    databaseName: text_analysis_db
    user: text_analysis_db_user

services:
  - type: web
    name: text_analysis
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn Text_Analysis.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: text_analysis_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true